version: 2.1
jobs:
  build:
    working_directory: ~/sortello/sortello
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run: npm run build:bundle
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run unit
# version: 2
# jobs:
#   build:
#     working_directory: ~/sortello/sortello
#     parallelism: 1
#     shell: /bin/bash --login
#     environment:
#       CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
#       CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
#       BASH_ENV: ~/.nvm/nvm.sh
#     docker:
#     - image: buildpack-deps:trusty
#     steps:
#     - checkout
#     - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
#     - run:
#         working_directory: ~/sortello/sortello
#         command: nvm install 6.7.0 && nvm alias default 6.7.0
#     - restore_cache:
#         keys:
#         - v1-dep-{{ .Branch }}-
#         - v1-dep-master-
#         - v1-dep-
#     - run: npm install
#     - run: npm install webpack@1.15.0 -g
#     - run: npm install webpack-cli@1.5.3 -g
#     - run: webpack
#     - save_cache:
#         key: v1-dep-{{ .Branch }}-{{ epoch }}
#         paths:
#         - vendor/bundle
#         - ~/virtualenvs
#         - ~/.m2
#         - ~/.ivy2
#         - ~/.bundle
#         - ~/.go_workspace
#         - ~/.gradle
#         - ~/.cache/bower
#         - ./node_modules
#     - run: npm run unit
#     - store_test_results:
#         path: /tmp/circleci-test-results
#     - store_artifacts:
#         path: /tmp/circleci-artifacts
#     - store_artifacts:
#         path: /tmp/circleci-test-results
# notify:
# webhooks:
# gitter hook
# - url: https://webhooks.gitter.im/e/7af68d739c18dcd6a78f
